a=int(input("Enter 1st number"))
b=int(input("Enter 2nd number"))
print(f"Addition of {a} and {b} is {a+b}")
print(f"Subtraction of {a} and {b} is {a-b}")
print(f"Multiplication of {a} and {b} is {a*b}")
print(f"Division of {a} and {b} is {a/b}")
print(f"Modulus of {a} and {b} is {a%b}")
print(f"Floor division of {a} and {b} is {a//b}")
print(f"exponentiation of {a} and {b} is {a**b}")
